name: "spha-cli"
description: "Action to run the SPHA command line tool."
inputs:
  args:
    description: "Arguments to pass to the SPHA CLI"
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/fraunhofer-iem/spha/cli:0.6.0"
  # Override the entrypoint to use a shell, which will properly 
  # split your input string into individual arguments.
  entrypoint: /bin/sh
  args:
    - -c
    # This executes the default entrypoint command and passes the args
    - "/app/spha-cli/bin/spha-cli ${{ inputs.args }}"
