name: "spha-cli"
description: "Action to run the SPHA command line tool."
inputs:
  scan-args:
    description: "Arguments to spha-cli, separated by new line. First argument must be a valid command ('transform' or 'calculate')"
    default: |-
      --help
runs:
  using: "docker"
  image: "docker://ghcr.io/fraunhofer-iem/spha-cli@latest"
  args:
    - ${{ inputs.scan-args }}