name: "spha-cli"
description: "Action to run the SPHA command line tool."
inputs:
  args:
    description: "Arguments to pass to the SPHA CLI (e.g., 'analyze --toolResultDir . --output kpis.json')"
    required: true


runs:
  using: "docker"
  image: "docker://ghcr.io/fraunhofer-iem/spha/cli:0.6.0"
  args:
    - ${{ inputs.args }}