name: "spha-cli"
description: "Action to run the SPHA command line tool."
inputs:
  tool:
    description: "Tool Name"
  inputFile:
    description: "Path to input file"
  output:
    description: "Path to output file"
    default: kpis.json

runs:
  using: "docker"
  image: "docker://ghcr.io/fraunhofer-iem/spha-cli:latest"
  args:
    - "transform"
    - "--tool"
    - ${{ inputs.tool }}
    - "--inputFile"
    - ${{ inputs.inputFile }}
    - "--output"
    - ${{ inputs.output }}
