name: "spha-cli"
description: "Action to run the SPHA command line tool."
inputs:
  source:
    description: "KPI Source Dir"
  output:
    description: "Path to output file"
    default: kpis.json

runs:
  using: "docker"
  image: "docker://ghcr.io/fraunhofer-iem/spha-cli:latest"
  args:
    - "calculate"
    - "--sourceDir"
    - ${{ inputs.tool }}
    - "--output"
    - ${{ inputs.output }}
